name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v1
        with:
          version: 1.4.1
      - name: Run Biome
        run: biome ci .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.19
      - run: bun install
      - run: bun run test
        env:
          PIKPAK_USERNAME: ${{secrets.PIKPAK_USERNAME}}
          PIKPAK_PASSWORD: ${{secrets.PIKPAK_PASSWORD}}
